import type { Metadata } from "next";
import "./globals.css";
import { jost, cinzel, merriweather, merriweatherSans, spaceGrotesk, bowlbyOneSC } from "./fonts";
import LayoutWrapper from "./LayoutWrapper";

export const metadata: Metadata = {
  title: "Daniel's Empire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${merriweather.variable} ${merriweatherSans.variable} ${spaceGrotesk.variable} ${bowlbyOneSC.variable} ${cinzel.variable} antialiased`}
        suppressHydrationWarning
      >
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
